server:
  port: 9090 #指定端口
spring:
  application:
    name: facerecog-service
  datasource:
    url: jdbc:mysql://132.232.108.138:3030/frdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: webdb
    password: sn18320110405
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    ehcache:
      config: ehcache.xml
mybatis:
  type-aliases-package: com.facerecog.pojo
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #支持驼峰式命名