server:
  port: 9090 #指定端口
  servlet:
    context-path: '/cpfr'
spring:
  application:
    name: facerecog-service
  datasource:
    url: jdbc:mysql://132.232.108.138:3030/frdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: webdb
    password: sn18320110405
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.facerecog.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/config-mybatis.xml

# 拦截路径
facerecog:
  filter:
    webExcludePaths:
      - /user/login
      - /user/nologin
      - /user/register
      - /ws
      - /app/**
      - /static/**
      - /index.html*
    appExcludePaths:
      - /app/device_register
      - /app/current_date
      - /app/disconnect