server:
  port: 8080 #指定端口
  servlet:
    context-path: '/cpfr'
    session:
      timeout: PT12H
logging:
  level:
    root: info
spring:
  application:
    name: facerecog-service
  datasource:
#    url: jdbc:mysql://152.136.134.235:3306/db_facerecog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    username: cjw
#    password: 363
    url: jdbc:mysql://127.0.0.1:3306/frdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 152.136.134.235
#    password: 363
#  rabbitmq:
#    host: 152.136.134.235
#    username: cjw
#    password: 363
#    virtual-host: /vh_cjw
#    template:
#      exchange: facerecog.test.exchange #不配置 默认交换机名称
  servlet:
    multipart:
      enabled: true
mybatis:
  type-aliases-package: com.facerecog.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/config-mybatis.xml
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  params: count=countSql
  page-size-zero: true
#fdfs:
#  so-timeout: 1501 # 超时时间
#  connect-timeout: 601 # 连接超时时间
#  thumb-image: # 缩略图
#    width: 60
#    height: 60
#  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
#    - 152.136.134.235:22122

# 自定义配置
facerecog:
  # 拦截路径
  filter:
    webExcludePaths:
      - /user/login
      - /user/nologin
      - /user/register
      - /ws
      - /app/**
      - /static/**
      - /index.html
    appExcludePaths:
      - /app/device_register
      - /app/current_date
      - /app/disconnect
  activatekey:
    arcSoftAppID: 'Co4RfcU3B6v2s9MvHWYtzJv2JAqmJwWgc9j1pGmNEgeu'
    arcSoftSdkKey: '7ijdL3ip6mS5bqx49jHZwz6CwK3osoznwCa6YPrkH5Dx'