server:
  port: 9090 #指定端口
  servlet:
    context-path: '/cpfr'
    session:
      timeout: 720
spring:
  application:
    name: facerecog-service
  datasource:
    url: jdbc:mysql://152.136.134.235:3306/db_facerecog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: cjw
    password: 363
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.facerecog.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/config-mybatis.xml
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  params: count=countSql
  page-size-zero: true

# 自定义配置
facerecog:
  # 拦截路径
  filter:
    webExcludePaths:
      - /user/login
      - /user/nologin
      - /user/register
      - /ws
      - /app/**
      - /static/**
      - /index.html
    appExcludePaths:
      - /app/device_register
      - /app/current_date
      - /app/disconnect
  activatekey:
    arcSoftAppID: 'Co4RfcU3B6v2s9MvHWYtzJv2JAqmJwWgc9j1pGmNEgeu'
    arcSoftSdkKey: '7ijdL3ip6mS5bqx49jHZwz6CwK3osoznwCa6YPrkH5Dx'