server:
  port: 9090 #指定端口
  servlet:
    context-path: '/cpfr'
    session:
      timeout: PT12H
logging:
  level:
    root: info
spring:
  application:
    name: facerecog-service
  datasource:
#    url: jdbc:mysql://132.232.108.138:3030/frdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    username: webdb
#    password: sn18320110405
    url: jdbc:mysql://111.230.151.37:3030/frdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: webdb
    password: sn18320110405
#    url: jdbc:mysql://127.0.0.1:3306/frdb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#    username: root
#    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
mybatis:
  type-aliases-package: com.facerecog.pojo
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/config-mybatis.xml
pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true
  params: count=countSql
  page-size-zero: true

# 自定义配置
facerecog:
  # 拦截路径
  filter:
    webExcludePaths:
      - /user/login
      - /user/nologin
      - /user/register
      - /ws
      - /app/**
      - /static/**
      - /index.html
    appExcludePaths:
      - /app/device_register
      - /app/current_date
      - /app/disconnect
  activatekey:
    arcSoftAppID: 'Co4RfcU3B6v2s9MvHWYtzJv2JAqmJwWgc9j1pGmNEgeu'
    arcSoftSdkKey: '7ijdL3ip6mS5bqx49jHZwz6CwK3osoznwCa6YPrkH5Dx'
